"""add synced_to_adx column to alerts

Revision ID: ffdb2750fe13
Revises: 4ec0f07ff36f
Create Date: 2026-03-09 19:11:28.943280

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffdb2750fe13"
down_revision: Union[str, Sequence[str], None] = "4ec0f07ff36f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alerts", sa.Column("synced_to_adx", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alerts", "synced_to_adx")
    # ### end Alembic commands ###
